[package]
name = "capinfo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
chrono = "0.4.41"
clap = { version = "4.5.41", features = ["derive"] }
env_logger.workspace = true
indicatif.workspace = true
indicatif-log-bridge.workspace = true
log.workspace = true
netkit = { path = "../../" }
polars = { version = "0.49.1", features = [
    "dtype-u8",
    "dtype-u16",
    # "json",
    "parquet",
    "rows",
    # "streaming",
    "lazy",
] }
tempfile = "3.20.0"
