[package]
name = "capinfo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.42"
clap = { version = "4.5.53", features = ["derive"] }
env_logger.workspace = true
indicatif.workspace = true
indicatif-log-bridge.workspace = true
log.workspace = true
netkit = { path = "../../" }
# Polars with minimal features for statistics and export
polars = { version = "0.52.0", default-features = false, features = [
    "dtype-u8",
    "dtype-u16",
    "parquet",
    "csv",
    "lazy",
] }
tempfile = "3.23.0"
